project_id = "cynoteapmqcfhzsuurhp"

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.generate-report-card-pdf]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.resend-invitation]
verify_jwt = true

[functions.admin-set-password]
verify_jwt = true
